version: 2
defaults: &defaults
  working_directory: ~/lagranfiestadelademocracia
  docker:
    - image: circleci/node:lts
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/lagranfiestadelademocracia
      - run:
          name: 'Install Dependencies'
          command: 'yarn install'
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/lagranfiestadelademocracia
      - run:
          name: build
          command: 'yarn build'
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/lagranfiestadelademocracia
      - run:
          name: Test
          command: 'yarn test'
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/lagranfiestadelademocracia
      - run:
          name: Lint
          command: 'yarn lint'
workflows:
  version: 2
  main_flow:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
